cc_library(
    name = "hello-greet",
    srcs = ["hello-greet.cc"],
    hdrs = ["hello-greet.h"],
    visibility = ["//main:__pkg__"],  # todo(cjh)
    includes = ['.'],  # 加'.' ，c++ include 时无需加路径名
)
